Subscription.create!(name: "basic", price: 10, description: "Basic plan. Casual boxes but your kitty will enjoy them.")
Subscription.create!(name: "standard", price: 30, description: "Standard plan. Standard boxes and your kitty will be satisfied them.")
Subscription.create!(name: "premium", price: 100, description: "Premium plan. Luxuary boxes and your kitty will be one of the most gorgeous kitties in the world!)

# Item.create!(title: "Cat snak", description: "Dr.Becker's Bites")
# Item.create!(title: "Dried Treats", description: "100% Pure Freeze Dried")
# Item.create!(title: "Cat treat", description: "My Mighty Lion Cat Treat by Waggers")
# Item.create!(title: "Steaks Treat", description: "Herring Steaks Treat by Snack 21")
# Item.create!(title: "Peppurroni Pizza", description: "Mad Cat Peppurroni Pizza by R2P Pet")
# Item.create!(title: "Catnip Duos", description: "PatchCat Catnip Duos by Patchwork Pet")
# Item.create!(title: "Desert Bug", description: "Desert Bug by Vitakraft Sun Seed")
# Item.create!(title: "Johnny Stick", description: "Johnny Stick by GiGwi")
# Item.create!(title: "Vial and Pouch", description: "Catnip Vial and Pouch by Tabby James")
# Item.create!(title: "Kittles", description: "Kittles Cat Treats, Chicken & Cranberries Recipe")
