Box.create!(level: 10, description: "This is a casual box but your kitty will enjoy this." )
Box.create!(level: 30, description: "This is a standard box and your kitty will be satisfied it.")
Box.create!(level: 100, description: "This is a luxuary box and your kitty will be one of the most gorgeous kitties in the world!")

Item.create!(title: "Cat snak", description: "Dr.Becker's Bites")
Item.create!(title: "Dried Treats", description: "100% Pure Freeze Dried")
Item.create!(title: "Cat treat", description: "My Mighty Lion Cat Treat by Waggers")
Item.create!(title: "Steaks Treat", description: "Herring Steaks Treat by Snack 21")
Item.create!(title: "Peppurroni Pizza", description: "Mad Cat Peppurroni Pizza by R2P Pet")
Item.create!(title: "Catnip Duos", description: "PatchCat Catnip Duos by Patchwork Pet")
Item.create!(title: "Desert Bug", description: "Desert Bug by Vitakraft Sun Seed")
Item.create!(title: "Johnny Stick", description: "Johnny Stick by GiGwi")
Item.create!(title: "Vial and Pouch", description: "Catnip Vial and Pouch by Tabby James")
Item.create!(title: "Kittles", description: "Kittles Cat Treats, Chicken & Cranberries Recipe")
